version: '3.8'

services:
    laravel:
        build:
            context: .
            dockerfile: ./docker/Dockerfile
        container_name: laravel_app
        ports:
            - "8000:8000"
        env_file:
            - ../nd-common-infra/.env
            - .env.local
        volumes:
            - ./:/var/www/html
            - ./docker/php.ini:/usr/local/etc/php/php.ini
        networks:
            - new-dealigence
        working_dir: /var/www/html
        command: php artisan serve --host=0.0.0.0 --port=8000

    nginx:
        image: nginx:latest
        container_name: laravel_nginx
        volumes:
            - ./:/var/www/html
            - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
        ports:
            - "80:80"
        depends_on:
            - laravel
        networks:
            - new-dealigence

networks:
    new-dealigence:
        external: true
